### Data Science Capstone
#####  Last update: December 18, 2016

-----------

##### Developed by: Naeem Khoshnevis
##### <a href="https://www.linkedin.com/in/datahacker">Linkedin</a>
##### <a href="https://github.com/Naeemkh">Github</a>


-----------

##### Summary

This web application is developed as Data Science Capstone by Johns Hopkins University. I used three sources of data including News, Blog, and Twitter data corpus. I generated 1-5 grams data set and predict the next word based on those ngrams. The program receive the input and reformat it into an appropriate string to predict the next word. I used Katz-Backoff model to back off for unobserved words. The first tab is a phone style presentation of the application. The application receive the input data instantaneously and predict and print out three most probable values. Second tab reports the 10 most probable words with their probability. Third tab plots 200 most probable words in a word cloud. 
The application is uploaded on the Shiny website, and documents are uploaded at the Gituhub repository.

Please read the full documentation from this <a href="https://rawgit.com/Naeemkh/DataScienceCapstone/master/full_documentation.html">link</a>.

-----------
Here are the related linkes:

<a href="https://github.com/Naeemkh/DataScienceCapstone"> Github Repository </a> \ \
<a href="https://rawgit.com/Naeemkh/DataScienceCapstone/master/FirstReport.html"> Milestone Report </a> \
<a href="https://rawgit.com/Naeemkh/DataScienceCapstone/master/full_documentation.html"> Final Report </a> \
<a href="http://rpubs.com/NaeemPub/238951"> Product Slide Deck </a> \







